// <auto-generated />
using System;
using EPS_Web_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EPS_Web_App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EPS_Web_App.Data.Models.AdminUser", b =>
                {
                    b.Property<long>("AdminUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("admin_user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdminUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("bit")
                        .HasColumnName("is_administrator");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("AdminUserId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_admin_user_username");

                    b.ToTable("admin_user", (string)null);
                });

            modelBuilder.Entity("EPS_Web_App.Data.Models.AstRecord", b =>
                {
                    b.Property<long>("AstRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ast_record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AstRecordId"));

                    b.Property<string>("AmikacinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("amikacin_int");

                    b.Property<string>("AmikacinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("amikacin_mic");

                    b.Property<string>("AmoxicillinClavulanateInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("amoxicillin_clavulanate_int");

                    b.Property<string>("AmoxicillinClavulanateMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("amoxicillin_clavulanate_mic");

                    b.Property<string>("AmpicillinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ampicillin_int");

                    b.Property<string>("AmpicillinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ampicillin_mic");

                    b.Property<string>("AmpicillinSulbactamInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ampicillin_sulbactam_int");

                    b.Property<string>("AmpicillinSulbactamMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ampicillin_sulbactam_mic");

                    b.Property<string>("AzithromycinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("azithromycin_int");

                    b.Property<string>("AzithromycinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("azithromycin_mic");

                    b.Property<string>("AztreonamInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("aztreonam_int");

                    b.Property<string>("AztreonamMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("aztreonam_mic");

                    b.Property<string>("BacterialIdentification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bacterial_identification");

                    b.Property<string>("CefazolinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefazolin_int");

                    b.Property<string>("CefazolinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefazolin_mic");

                    b.Property<string>("CefepimeInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefepime_int");

                    b.Property<string>("CefepimeMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefepime_mic");

                    b.Property<string>("CefotaximeClavulanateInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefotaxime_clavulanate_int");

                    b.Property<string>("CefotaximeClavulanateMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefotaxime_clavulanate_mic");

                    b.Property<string>("CefotaximeInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefotaxime_int");

                    b.Property<string>("CefotaximeMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefotaxime_mic");

                    b.Property<string>("CefotetanInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefotetan_int");

                    b.Property<string>("CefotetanMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefotetan_mic");

                    b.Property<string>("CefoxitinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefoxitin_int");

                    b.Property<string>("CefoxitinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefoxitin_mic");

                    b.Property<string>("CeftazidimeClavulanateInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ceftazidime_clavulanate_int");

                    b.Property<string>("CeftazidimeClavulanateMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ceftazidime_clavulanate_mic");

                    b.Property<string>("CeftazidimeInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ceftazidime_int");

                    b.Property<string>("CeftazidimeMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ceftazidime_mic");

                    b.Property<string>("CeftolozaneTazobactamInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ceftolozane_tazobactam_int");

                    b.Property<string>("CeftolozaneTazobactamMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ceftolozane_tazobactam_mic");

                    b.Property<string>("CeftriaxoneInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ceftriaxone_int");

                    b.Property<string>("CeftriaxoneMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ceftriaxone_mic");

                    b.Property<string>("CefuroximeInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefuroxime_int");

                    b.Property<string>("CefuroximeMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cefuroxime_mic");

                    b.Property<string>("CephalothinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cephalothin_int");

                    b.Property<string>("CephalothinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cephalothin_mic");

                    b.Property<string>("ChloramphenicolInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("chloramphenicol_int");

                    b.Property<string>("ChloramphenicolMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("chloramphenicol_mic");

                    b.Property<string>("CiprofloxacinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ciprofloxacin_int");

                    b.Property<string>("CiprofloxacinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ciprofloxacin_mic");

                    b.Property<string>("ColistinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("colistin_int");

                    b.Property<string>("ColistinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("colistin_mic");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())", "DF_ast_created_at");

                    b.Property<string>("DiagnosticTest")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diagnostic_test");

                    b.Property<string>("DiarrheaMedicationPast72h")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diarrhea_medication_past_72h");

                    b.Property<string>("ErtapenemInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ertapenem_int");

                    b.Property<string>("ErtapenemMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ertapenem_mic");

                    b.Property<string>("EsblStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("esbl_status");

                    b.Property<string>("FosfomycinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fosfomycin_int");

                    b.Property<string>("FosfomycinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fosfomycin_mic");

                    b.Property<string>("GatifloxacinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("gatifloxacin_int");

                    b.Property<string>("GatifloxacinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("gatifloxacin_mic");

                    b.Property<string>("GentamicinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("gentamicin_int");

                    b.Property<string>("GentamicinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("gentamicin_mic");

                    b.Property<string>("GtdStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gtd_status");

                    b.Property<string>("IllnessFunctionalImpact")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("illness_functional_impact");

                    b.Property<string>("ImipenemInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("imipenem_int");

                    b.Property<string>("ImipenemMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("imipenem_mic");

                    b.Property<string>("Lan")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("lan");

                    b.Property<string>("LevofloxacinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("levofloxacin_int");

                    b.Property<string>("LevofloxacinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("levofloxacin_mic");

                    b.Property<string>("LinkageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("linkage_status")
                        .HasDefaultValue("Unlinked", "DF_ast_linkage_status");

                    b.Property<string>("MdrStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mdr_status");

                    b.Property<string>("MedicationsPast72h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("medications_past_72h");

                    b.Property<string>("MeropenemInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("meropenem_int");

                    b.Property<string>("MeropenemMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("meropenem_mic");

                    b.Property<string>("MonthCollected")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("month_collected");

                    b.Property<string>("MoxifloxacinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("moxifloxacin_int");

                    b.Property<string>("MoxifloxacinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("moxifloxacin_mic");

                    b.Property<string>("NalidixicAcidInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nalidixic_acid_int");

                    b.Property<string>("NalidixicAcidMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nalidixic_acid_mic");

                    b.Property<string>("NitrofurantoinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nitrofurantoin_int");

                    b.Property<string>("NitrofurantoinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nitrofurantoin_mic");

                    b.Property<string>("NorfloxacinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("norfloxacin_int");

                    b.Property<string>("NorfloxacinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("norfloxacin_mic");

                    b.Property<string>("ParasiteIdentification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parasite_identification");

                    b.Property<string>("ParticipantType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("participant_type");

                    b.Property<string>("PiperacillinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("piperacillin_int");

                    b.Property<string>("PiperacillinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("piperacillin_mic");

                    b.Property<string>("PiperacillinTazobactamInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("piperacillin_tazobactam_int");

                    b.Property<string>("PiperacillinTazobactamMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("piperacillin_tazobactam_mic");

                    b.Property<string>("RifampicinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("rifampicin_int");

                    b.Property<string>("RifampicinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("rifampicin_mic");

                    b.Property<string>("SiteCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("site_code");

                    b.Property<string>("SpecimenId")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("specimen_id");

                    b.Property<string>("TetracyclineInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tetracycline_int");

                    b.Property<string>("TetracyclineMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tetracycline_mic");

                    b.Property<string>("TicarcillinClavulanateInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ticarcillin_clavulanate_int");

                    b.Property<string>("TicarcillinClavulanateMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ticarcillin_clavulanate_mic");

                    b.Property<string>("TigecyclineInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tigecycline_int");

                    b.Property<string>("TigecyclineMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tigecycline_mic");

                    b.Property<string>("TobramycinInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tobramycin_int");

                    b.Property<string>("TobramycinMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tobramycin_mic");

                    b.Property<string>("TrimethoprimSulfamethoxazoleInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trimethoprim_sulfamethoxazole_int");

                    b.Property<string>("TrimethoprimSulfamethoxazoleMic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trimethoprim_sulfamethoxazole_mic");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.Property<string>("ViralIdentification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("viral_identification");

                    b.HasKey("AstRecordId");

                    b.HasIndex(new[] { "Lan" }, "IX_ast_lan");

                    b.HasIndex(new[] { "SiteCode" }, "IX_ast_site_code");

                    b.HasIndex(new[] { "SpecimenId" }, "IX_ast_specimen_id");

                    b.ToTable("ast_record", (string)null);
                });

            modelBuilder.Entity("EPS_Web_App.Data.Models.DataEntryAudit", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("(sysutcdatetime())", "DF_audit_changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("changed_by");

                    b.Property<string>("FieldName")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("RecordKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("record_key");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("record_type");

                    b.HasKey("AuditId");

                    b.HasIndex(new[] { "RecordType", "RecordKey" }, "IX_audit_record_key");

                    b.ToTable("data_entry_audit", (string)null);
                });

            modelBuilder.Entity("EPS_Web_App.Data.Models.FormVersion", b =>
                {
                    b.Property<long>("FormVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("form_version_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FormVersionId"));

                    b.Property<DateTime>("EffectiveFrom")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("effective_to");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("form_name");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_current")
                        .HasDefaultValue(true, "DF_form_version_current");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("version_number");

                    b.HasKey("FormVersionId");

                    b.HasIndex(new[] { "FormName", "VersionNumber" }, "UQ_form_version")
                        .IsUnique();

                    b.ToTable("form_version", (string)null);
                });

            modelBuilder.Entity("EPS_Web_App.Data.Models.LookupValue", b =>
                {
                    b.Property<long>("LookupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("lookup_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LookupId"));

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("is_active")
                        .HasDefaultValue(true, "DF_lookup_is_active");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lookup_code");

                    b.Property<string>("LookupGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lookup_group");

                    b.Property<string>("LookupLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lookup_label");

                    b.HasKey("LookupId");

                    b.HasIndex(new[] { "LookupGroup", "LookupCode" }, "UQ_lookup_group_code")
                        .IsUnique();

                    b.ToTable("lookup_value", (string)null);
                });

            modelBuilder.Entity("EPS_Web_App.Data.Models.QuestionnaireEntry", b =>
                {
                    b.Property<long>("QuestionnaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("questionnaire_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("QuestionnaireId"));

                    b.Property<string>("AbdominalCramps")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abdominal_cramps");

                    b.Property<string>("AbdominalCrampsDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abdominal_cramps_duration");

                    b.Property<string>("AbdominalCrampsSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abdominal_cramps_severity");

                    b.Property<string>("AdditionalSymptoms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("additional_symptoms");

                    b.Property<string>("AdditionalSymptomsSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("additional_symptoms_severity");

                    b.Property<string>("AdmissionDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admission_date");

                    b.Property<string>("AdmissionTime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admission_time");

                    b.Property<string>("Admitted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admitted");

                    b.Property<string>("AdultConsciousnessResponse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adult_consciousness_response");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("age");

                    b.Property<string>("BacterialIdentification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bacterial_identification");

                    b.Property<string>("BloodPressure")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("blood_pressure");

                    b.Property<string>("BloodyStool")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bloody_stool");

                    b.Property<string>("BloodyStoolDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bloody_stool_duration");

                    b.Property<string>("BodyTemperature")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_temperature");

                    b.Property<string>("BodyWeight")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_weight");

                    b.Property<string>("CapillaryRefill")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("capillary_refill");

                    b.Property<string>("ChildAssessment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("child_assessment");

                    b.Property<string>("ChildConsciousnessResponse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("child_consciousness_response");

                    b.Property<string>("ChildDrinkingBreastfeeding")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("child_drinking_breastfeeding");

                    b.Property<string>("ChildRestlessness")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("child_restlessness");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())", "DF_questionnaire_created_at");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DiarrheaDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diarrhea_duration");

                    b.Property<string>("DischargeDeathDiagnosis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discharge_death_diagnosis");

                    b.Property<string>("Disposition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("disposition");

                    b.Property<string>("DispositionDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("disposition_date");

                    b.Property<string>("DispositionTime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("disposition_time");

                    b.Property<string>("ExcessiveGas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("excessive_gas");

                    b.Property<string>("ExcessiveGasDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("excessive_gas_duration");

                    b.Property<string>("ExcessiveGasSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("excessive_gas_severity");

                    b.Property<string>("FecalIncontinence")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fecal_incontinence");

                    b.Property<string>("FecalIncontinenceDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fecal_incontinence_duration");

                    b.Property<string>("FecalIncontinenceSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fecal_incontinence_severity");

                    b.Property<string>("Fever")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fever");

                    b.Property<string>("FeverDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fever_duration");

                    b.Property<string>("FeverSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fever_severity");

                    b.Property<string>("FirstSymptom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_symptom");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gender");

                    b.Property<string>("GeneralCondition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("general_condition");

                    b.Property<string>("Headache")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("headache");

                    b.Property<string>("HeadacheDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("headache_duration");

                    b.Property<string>("HeadacheSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("headache_severity");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("height");

                    b.Property<string>("HivStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hiv_status");

                    b.Property<string>("IllnessFunctionalImpact")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("illness_functional_impact");

                    b.Property<string>("IsolationDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("isolation_date");

                    b.Property<string>("IvRehydration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("iv_rehydration");

                    b.Property<string>("JointAches")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("joint_aches");

                    b.Property<string>("JointAchesDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("joint_aches_duration");

                    b.Property<string>("JointAchesSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("joint_aches_severity");

                    b.Property<string>("Lan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lan");

                    b.Property<string>("Lightheadedness")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lightheadedness");

                    b.Property<string>("LightheadednessDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lightheadedness_duration");

                    b.Property<string>("LightheadednessSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lightheadedness_severity");

                    b.Property<string>("LooseStools24h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loose_stools_24h");

                    b.Property<string>("LooseStools8h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loose_stools_8h");

                    b.Property<string>("LossOfAppetite")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loss_of_appetite");

                    b.Property<string>("LossOfAppetiteDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loss_of_appetite_duration");

                    b.Property<string>("MainJob")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("main_job");

                    b.Property<string>("MalaiseFatigue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("malaise_fatigue");

                    b.Property<string>("MalaiseFatigueDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("malaise_fatigue_duration");

                    b.Property<string>("MalaiseFatigueSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("malaise_fatigue_severity");

                    b.Property<string>("MalnutritionStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("malnutrition_status");

                    b.Property<string>("MaxLooseStools24h")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("max_loose_stools_24h");

                    b.Property<string>("Muac")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("muac");

                    b.Property<string>("MucousStool")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mucous_stool");

                    b.Property<string>("MuscleAches")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("muscle_aches");

                    b.Property<string>("MuscleAchesDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("muscle_aches_duration");

                    b.Property<string>("MuscleAchesSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("muscle_aches_severity");

                    b.Property<string>("Nausea")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nausea");

                    b.Property<string>("NauseaDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nausea_duration");

                    b.Property<string>("NauseaSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nausea_severity");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("occupation");

                    b.Property<string>("OralRehydration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oral_rehydration");

                    b.Property<string>("OtherRotavirusVaccineDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("other_rotavirus_vaccine_date");

                    b.Property<string>("OtherRotavirusVaccineStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("other_rotavirus_vaccine_status");

                    b.Property<string>("OtherSymptoms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("other_symptoms");

                    b.Property<string>("OtherSymptomsSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("other_symptoms_severity");

                    b.Property<string>("OtherSymptomsSpecified")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("other_symptoms_specified");

                    b.Property<string>("OtherTreatment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("other_treatment");

                    b.Property<string>("OutpatientTreatment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("outpatient_treatment");

                    b.Property<string>("PainfulStrainingDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("painful_straining_duration");

                    b.Property<string>("PainfulStrainingSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("painful_straining_severity");

                    b.Property<string>("PainfulStrainingStool")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("painful_straining_stool");

                    b.Property<string>("ParasiteIdentification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parasite_identification");

                    b.Property<string>("PatientClinicalState")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("patient_clinical_state");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rank");

                    b.Property<string>("Residence")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("residence");

                    b.Property<string>("RespiratoryRate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("respiratory_rate");

                    b.Property<string>("RiceWaterStool")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rice_water_stool");

                    b.Property<string>("RotavirusDose1Date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rotavirus_dose_1_date");

                    b.Property<string>("RotavirusDose1Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rotavirus_dose_1_status");

                    b.Property<string>("RotavirusDose2Date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rotavirus_dose_2_date");

                    b.Property<string>("RotavirusDose2Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rotavirus_dose_2_status");

                    b.Property<string>("SiteCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("site_code");

                    b.Property<string>("SkinPinchBack")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("skin_pinch_back");

                    b.Property<string>("SpecimenId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("specimen_id");

                    b.Property<string>("StoolUrgency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stool_urgency");

                    b.Property<string>("StoolUrgencyDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stool_urgency_duration");

                    b.Property<string>("StoolUrgencySeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stool_urgency_severity");

                    b.Property<string>("SymptomOnsetDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symptom_onset_date");

                    b.Property<string>("SymptomOnsetTime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symptom_onset_time");

                    b.Property<string>("TreatmentGiven")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("treatment_given");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.Property<string>("ViralIdentification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("viral_identification");

                    b.Property<string>("Vomiting")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vomiting");

                    b.Property<string>("VomitingCount")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vomiting_count");

                    b.Property<string>("VomitingDuration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vomiting_duration");

                    b.Property<string>("VomitingSeverity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vomiting_severity");

                    b.Property<string>("WaterSourceType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("water_source_type");

                    b.Property<string>("WaterTreatment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("water_treatment");

                    b.HasKey("QuestionnaireId");

                    b.HasIndex(new[] { "Lan" }, "IX_questionnaire_lan");

                    b.HasIndex(new[] { "SiteCode" }, "IX_questionnaire_site_code");

                    b.HasIndex(new[] { "SpecimenId" }, "UQ_questionnaire_specimen_id")
                        .IsUnique();

                    b.ToTable("questionnaire_entry", (string)null);
                });

            modelBuilder.Entity("EPS_Web_App.Data.Models.ReconciliationAlert", b =>
                {
                    b.Property<long>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("alert_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AlertId"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("alert_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())", "DF_reconciliation_created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("priority")
                        .HasDefaultValue("Medium", "DF_reconciliation_priority");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("resolved_by");

                    b.Property<string>("SourceRecord")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("source_record");

                    b.Property<string>("SpecimenId")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("specimen_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status")
                        .HasDefaultValue("Open", "DF_reconciliation_status");

                    b.HasKey("AlertId");

                    b.HasIndex(new[] { "SpecimenId" }, "IX_reconciliation_specimen_id");

                    b.HasIndex(new[] { "Status" }, "IX_reconciliation_status");

                    b.ToTable("reconciliation_alert", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
